version: '3.8'

services:
  # MongoDB service
  mongo: 
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db:rw

  # Node API service
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MongoDB_URI: mongodb://mongo:27017
      DB_Name: yugioh
      NAME: production
    depends_on:
      - mongo

volumes:
  mongo: {}

# version: '3.8'

# services:
#   mongo:
#     container_name: mongo
#     image: mongo
#     restart: always
#     ports:
#       - '27017:27017'
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: localdev
#     volumes:
#       - db:/data/db:rw

#   mongo-express:
#     container_name: mongo_express
#     image: mongo-express
#     restart: always
#     ports:
#       - '8081:8081'
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: localdev
#       ME_CONFIG_MONGODB_URL: mongodb://root:localdev@mongo:27017/

# volumes:
#   db:
