# fly.toml app configuration file generated for yugioh-backend on 2023-05-01T17:16:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yugioh-backend"
primary_region = "sea"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
