# @name login

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "a@example.com",
    "password": "hello123"
}

###

# @name register

POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "email": "registest@example.com",
    "password": "hello123"
}

###

@loginToken = {{login.response.body.jwt}}
@registerToken = {{register.response.body.jwt}}

# @name me
GET http://localhost:3000/me HTTP/1.1
Authorization: Bearer {{loginToken}}

###

# @name me
GET http://localhost:3000/me HTTP/1.1
Authorization: Bearer {{registerToken}}

###